### ISSUE TITLE
Passwords not working

### ISSUE THREAD

**Issue by cguerin** [joeaudette/cloudscribe.StarterKits#27] opened 2017-04-13 20:25 UTC
I'm using Cloudscribe ID server ef -- and login is not working when I create a New Site, on that site.

I get "Unexpected error" when I enter that site and click login. 

Made sure that I'd logged completely out of the admin before trying.

Any ideas why it's not working?

**Comment by joeaudette** [comment] 2017-04-13 20:32
I'm not able to produce the problem. There should be no need to log out of one tenant to login to another.
I suggest login to the root tenant and check the log for the error details under Administration > System Info > System Log

maybe with the error detail I would know what the problem is.

**Comment by cguerin** [comment] 2017-04-13 21:15
Here's what's happening - not showing up in error logs...

https://www.screencast.com/t/TbSI5bA2x

**Comment by joeaudette** [comment] 2017-04-13 22:28
thanks for the screencast to clarify.

try making the folder name for the second site all lower case and keeping it lower case in the url 
/testcontent and see if that makes any difference. I do think it is case sensitive and maybe the error is a 404.
 It is recommended to use lower case urls and configured for that in startup so the folder name for the site should also be lower case.

from the site list you should be able to open the other site by right clicking the link and open in new tab and you should not have to logout of the first site

**Comment by joeaudette** [comment] 2017-04-17 14:15
can you confirm if changing to lower case folder name solved the problem?

**Comment by joeaudette** [comment] 2017-04-20 12:57
I have confirmed by my own testing that I could produce the problem by using mixed case folder name and could solve the problem by changing the folder segment to lower case and restarting the app.

I have implement a change to force the folder segment to always be lower case, so this will be solved in the next nuget publish. Technically it would work with mixed case folder segment if it was not configured for the routing to change it to lower case. However then the user would always have to use the correct mixed case or it would not resolve the tenant and would lead to errors. In general it is best to always use lower case urls for seo reasons and also for cross platform reasons since urls are case sensitive on linux but not on windows, so if you start with mixed case urls on windows and later move to linux hosting it could be problematic. In any case the folder segment lookup in the db for tenant resolution is case sensitive.

I am closing this issue, thanks for reporting the problem

**Closed as completed by joeaudette** 2017-04-20 12:57 UTC
